/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as LevelsLevelRouteImport } from './routes/levels.$level'
import { Route as LevelsLevelSemesterRouteImport } from './routes/levels.$level.$semester'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelRoute = LevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelSemesterRoute = LevelsLevelSemesterRouteImport.update({
  id: '/$semester',
  path: '/$semester',
  getParentRoute: () => LevelsLevelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/upload': typeof UploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRouteWithChildren
  '/levels/$level/$semester': typeof LevelsLevelSemesterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/upload': typeof UploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRouteWithChildren
  '/levels/$level/$semester': typeof LevelsLevelSemesterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/upload': typeof UploadRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/levels/$level': typeof LevelsLevelRouteWithChildren
  '/levels/$level/$semester': typeof LevelsLevelSemesterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/upload'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/levels/$level/$semester'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/upload'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/levels/$level/$semester'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/upload'
    | '/courses/$courseId'
    | '/levels/$level'
    | '/levels/$level/$semester'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  UploadRoute: typeof UploadRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  LevelsLevelRoute: typeof LevelsLevelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level': {
      id: '/levels/$level'
      path: '/levels/$level'
      fullPath: '/levels/$level'
      preLoaderRoute: typeof LevelsLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$level/$semester': {
      id: '/levels/$level/$semester'
      path: '/$semester'
      fullPath: '/levels/$level/$semester'
      preLoaderRoute: typeof LevelsLevelSemesterRouteImport
      parentRoute: typeof LevelsLevelRoute
    }
  }
}

interface LevelsLevelRouteChildren {
  LevelsLevelSemesterRoute: typeof LevelsLevelSemesterRoute
}

const LevelsLevelRouteChildren: LevelsLevelRouteChildren = {
  LevelsLevelSemesterRoute: LevelsLevelSemesterRoute,
}

const LevelsLevelRouteWithChildren = LevelsLevelRoute._addFileChildren(
  LevelsLevelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  UploadRoute: UploadRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  LevelsLevelRoute: LevelsLevelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
